// app/layout.tsx
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { UserDetailProvider } from "@/context/UserDetailContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  // weight: ["100","200","300","400","500","600","700","800","900"], // optional if you need specific weights
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" >
      <body className={outfit.className}>
        <ConvexClientProvider>
          <UserDetailProvider>
          
        {children}
        </UserDetailProvider>
        </ConvexClientProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
